### ISSUE TITLE
Tests are currently failing to run

### ISSUE THREAD

**Issue by sareh** [BBC-archive/psammead#25]
**Describe the bug**

**To Reproduce**

1. `npm install` `npm run test`
2. See error `Cannot find module 'enzyme' from 'index.spec.js'`

**Expected behavior**
I should get no installation warnings. The tests should all run

**Screenshots**
```
npm run test

> psammead@0.1.0 test /Users/heidas03/dev/psammead
> jest --verbose

 FAIL  packages/example-button/src/index.spec.js
  ● Test suite failed to run

    Cannot find module 'enzyme' from 'index.spec.js'

      1 | import React from 'react'
    > 2 | import { mount } from 'enzyme'
        | ^
      3 |
      4 | import Button from '.'
      5 |

      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:221:17)
      at Object.<anonymous> (packages/example-button/src/index.spec.js:2:1)

Test Suites: 1 failed, 1 total
```

- [x] Initially labelled with ["bug"](https://github.com/BBC-News/psammead/labels/bug)

**Comment by ChrisBAshton** [comment]
May conflict with #16 - if we remove Enzyme, we don't have to waste effort fixing the tests for an example component! :)

**Comment by ChrisBAshton** [comment]
Superseded by #16, as discussed on Slack 👍
